### PR TITLE
optimize：optimize config module code

### PR DESCRIPTION
**Pull request by lingxiao-wu**
## PR Type
Code style update (formatting, local variables).

## Describe what this PR does for and how you did.
optimize config module code

## Checklist

- [x] Add copyright holder at the beginning of .class file if it is new.
- [x] Add information of this PR to CHANGELOG.md in root of project.
- [ ] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [x] Add documentation in javadoc in code or comment below the PR if necessary.
- [x] Add your name as @author to the beginning of .class file.

### CODE REVIEW

**Review by SkyeBeFreeman — APPROVED** [review]

**Comment by SkyeBeFreeman** [comment]
@lingxiao-wu 单测覆盖率需要提升~

**Comment by lingxiao-wu** [comment]
> @lingxiao-wu 单测覆盖率需要提升~

好的，我也发现spring这个package下很多类都没有被单元测试覆盖到，我针对这个package提升一下覆盖率

**Comment by lingxiao-wu** [comment]
> @lingxiao-wu 单测覆盖率需要提升~

好的，我也发现spring这个package下很多类都没有被单元测试覆盖到，我针对这个package提升一下覆盖率

**Review by lepdou — COMMENTED** [review]
LGTM

**Review by lepdou — APPROVED** [review]

**Pull request merged**
