### PR TITLE
UT add metadata-transfer unit test

### PR DESCRIPTION
**Pull request by shouyuwang**
## PR Type
UT

## Describe what this PR does for and how you did.
add metadata-transfer unit test
## Adding the issue link (#xxx) if possible.
issue #238 
## Checklist

- [x] Add copyright holder at the beginning of .class file if it is new.
- [x] Add information of this PR to CHANGELOG.md in root of project.
- [x] All junit tests passing.
- [x] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [ ] Will Pull Request to branch of 2020.0 and 2021.0.
- [ ] Add documentation in javadoc in code or comment below the PR if necessary.
- [ ] Add your name as @author to the beginning of .class file.

### CODE REVIEW

**Comment by SkyeBeFreeman** [comment]
why no coverage report? 0.0

**Comment by SkyeBeFreeman** [comment]
应该像 #282 一样一个覆盖率报告才对🤔

**Comment by SkyeBeFreeman** [comment]
好像要等一会才能看到，https://codecov.io/gh/Tencent/spring-cloud-tencent/tree/f5dd3346cab31390f3c6d967c580cdca0f2e0d92

**Comment by shouyuwang** [comment]
> 好像要等一会才能看到，明天再详细看看。
> 
> https://codecov.io/gh/Tencent/spring-cloud-tencent/tree/f5dd3346cab31390f3c6d967c580cdca0f2e0d92

cover

**Comment by SkyeBeFreeman** [comment]
可以先把必选的checklist点一下哈～

**Comment by shouyuwang** [comment]
这个我怀疑是多次commit导致的，刚才rebase下发现有问题，就给close了，重新提了个pr

**Pull request closed without merging**
