### PR TITLE
format constatns UTF-8

### PR DESCRIPTION
**Pull request by weihubeats**
## Describe what this PR does for and how you did.
Use jdk constants instead of magic variables

## Adding the issue link (#xxx) if possible.
https://github.com/Tencent/spring-cloud-tencent/issues/312

## Checklist

- [x] Add copyright holder at the beginning of .class file if it is new.
- [x] Add information of this PR to CHANGELOG.md in root of project.
- [x] All junit tests passing.
- [x] Coverage from `Codecov Report` should not decrease.

### CODE REVIEW

**Review by SkyeBeFreeman — APPROVED** [review]
LGTM.

**Comment by SkyeBeFreeman** [comment]
Will you cherry-pick to branch of 2020 and 2021?

**Comment by SkyeBeFreeman** [comment]
@weihubeats I have cherry-picked to branch of 2020 and 2021.

**Comment by weihubeats** [comment]
ok thanks, i forgot about this task

**Comment by SkyeBeFreeman** [comment]
> ok thanks, i forgot about this task

It's ok.😄

**Pull request merged**
