### PR TITLE
[Feature] Add disposable metadata transfer support .(main)

### LINKED ISSUE #293: metadata-transfer中传递覆盖问题
A服务和B服务中进行设置了参数`data`进行传递，A服务中`data`=10，B服务中`data`=100。当A服务调用B服务的时候，B服务的`data`是否要进行覆盖？

### PR DESCRIPTION
**Pull request by misselvexu**
## PR Type
Feature.

## Describe what this PR does for and how you did.
- Add disposable metadata transfer support .

## Adding the issue link (#xxx) if possible.
Fixed #293 .

## Note
- Usage

```yaml
spring:
  application:
    name: MetadataCallerService
  cloud:
    tencent:
      metadata:
        # Defined your metadata keys & values
        content:
          # Example: intransitive
          CUSTOM-METADATA-KEY-LOCAL: CUSTOM-VALUE-LOCAL
          # Example: disposable (one-time)
          CUSTOM-METADATA-KEY-DISPOSABLE: CUSTOM-VALUE-DISPOSABLE
          # Example: transitive
          CUSTOM-METADATA-KEY-TRANSITIVE: CUSTOM-VALUE-TRANSITIVE
        # Assigned which metadata key-value will be passed along the link
        transitive:
          - CUSTOM-METADATA-KEY-TRANSITIVE
        #  Assigned disposable key (one-time)
        disposable:
          - CUSTOM-METADATA-KEY-DISPOSABLE
```

## Checklist

- [x] Add copyright holder at the beginning of .class file if it is new.
- [x] Add information of this PR to CHANGELOG.md in root of project.
- [x] All junit tests passing.
- [ ] Coverage from `Codecov Report` should not decrease.

## Checklist (Optional)

- [x] Will Pull Request to branch of 2020.0 and 2021.0.
- [x] Add documentation in javadoc in code or comment below the PR if necessary.
- [x] Add your name as @author to the beginning of .class file.

### CODE REVIEW

**Review by lepdou — APPROVED** [review]
LGTM

**Review by SkyeBeFreeman — CHANGES_REQUESTED** [review]
metadata-example现在变成调用链的形式，不应该用callee和callee2来表述，这与其他的callee和callee2是平级有区别。是不是参考灰度发布example的front、middle、back这样层级表述更明显的词汇来命名example？

**Comment by misselvexu** [comment]
> metadata-example现在变成调用链的形式，不应该用callee和callee2来表述，这与其他的callee和callee2是平级有区别。是不是参考灰度发布example的front、middle、back这样层级表述更明显的词汇来命名example？

copy that,

**Review by SkyeBeFreeman — COMMENTED** [review]
看起来好像没有在路由添加一次性路由的使用？

**Comment by misselvexu** [comment]
> 看起来好像没有在路由添加一次性路由的使用？

@SkyeBeFreeman  Routing usage scenarios that will be explored in the week .

**Review by SkyeBeFreeman — APPROVED** [review]
LGTM.

**Comment by SkyeBeFreeman** [comment]
> > 看起来好像没有在路由添加一次性路由的使用？
> 
> @SkyeBeFreeman Routing usage scenarios that will be discuss in the week .

Don't use disposable metadata in serviuce router at this version.

**Pull request merged**
