### PR TITLE
optimize ServiceRuleManager

### LINKED ISSUE #822: 【需求认领】优化ServiceRuleManager获取规则的逻辑
**What is the feature you want to add?**

将`ServiceRuleManager`中`getServiceRateLimitRule`和`getServiceRouterRule`两个方法中获取服务规则（限流规则、路由规则）的实现逻辑进行优化，去掉`BaseFlow.syncGetResources`这类偏底层的调用，改为使用`ConsumerAPI.getServiceRule`的实现。

**Why do you want to add this feature?**

原有的方式没有对入参进行校验，有代码运行异常的风险。

**How to implement this feature?**

**Additional context**

无。

### PR DESCRIPTION
**Pull request by DoubleLuXu**
## Describe what this PR does for and how you did.
优化ServiceRuleManger获取规则逻辑
## Adding the issue link (#xxx) if possible.
https://github.com/Tencent/spring-cloud-tencent/issues/822

## Checklist

- [ ] Add information of this PR to CHANGELOG.md in root of project.
- [ ] Add documentation in javadoc or comment below the PR if necessary.

### CODE REVIEW

**Comment by SkyeBeFreeman** [comment]
@DoubleLuXu please resolve the conflicts.

**Comment by SkyeBeFreeman** [comment]
@DoubleLuXu please fix the junit error.

**Comment by DoubleLuXu** [comment]
> @DoubleLuXu please fix the junit error.

嗯，我在编译呢，稍等

**Review by SkyeBeFreeman — APPROVED** [review]
LGTM.

**Review by chuntaojun — APPROVED** [review]

**Comment by SkyeBeFreeman** [comment]
@DoubleLuXu Cherry-pick to the 2022 and 2020 branch if it is convenient.

**Pull request merged**
