### PR TITLE
solve the chaos code problem on rejectTips in 2020.0

### PR DESCRIPTION
**Pull request by cheese8**
PR Type
Bugfix.

Describe what this PR does for and how you did.
solve the chaos code problem on rejectTips

Does this PR be associated with issue? If so, please adding the issue link below.
Fix https://github.com/Tencent/spring-cloud-tencent/issues/278

### CODE REVIEW

**Comment by SkyeBeFreeman** [comment]
@cheese8 please check #278 new comment before this PR.

**Comment by SkyeBeFreeman** [comment]
直接把main分支后来改成html和ReactiveFilter的支持一起提交吧

**Comment by cheese8** [comment]
> 直接把main分支后来改成html和ReactiveFilter的支持一起提交吧

OK, not hurry,  would be refactored after #285 finished.

**Review by SkyeBeFreeman — APPROVED** [review]
LGTM.

**Comment by cheese8** [comment]
> 2021分支方便提交一下不？😆

OK

**Pull request merged**
