### PR TITLE
fix: ratelimit-callee-service UnknownHostException: RateLimitCalleeService

### PR DESCRIPTION
**Pull request by shouyuwang**
## Describe what this PR does for and how you did.
add `spring-cloud-starter-tencent-polaris-discovery` dependency.

### Checklist
- [ ] Code compiles correctly
- [ ] Pull Request has submit to 2020.0 and Greenwich
- [ ] Create at least one junit test if possible
- [ ] All tests passing
- [ ] Extend documentation if necessary
- [ ] Add myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by SkyeBeFreeman** [comment]
RateLimitCalleeService has no need to register to Polaris. It can run standalone to show the ability of rate limit.

**Comment by shouyuwang** [comment]
> RateLimitCalleeService has no need to register to Polaris. It can run standalone to show the ability of rate limit.

BusinessController中的invokeInfo方法进行调用的时候应该是读取的appName。
```
@Autowired
private RestTemplate restTemplate;

@Value("${spring.application.name}")
private String appName;
ResponseEntity<String> entity = restTemplate.getForEntity(
						"http://" + appName + "/business/info", String.class);
```
这时候的restTemplate，理论上是需要lb的啊。
```
@Bean
@LoadBalanced
public RestTemplate restTemplate() {
    return new RestTemplate();
}
```
启动类中的这个resttemplate 也是需要lb的啊，要是不引入`spring-cloud-starter-tencent-polaris-discovery`那lb注解也不生效吧。

**Comment by SkyeBeFreeman** [comment]
这里不应当提供服务调用的例子，我明天看下这里的代码提交哈～

**Comment by shouyuwang** [comment]
> 这里不应当提供服务调用的例子，我明天看下这里的代码提交哈～

ok，辛苦

**Comment by SkyeBeFreeman** [comment]
> > 这里不应当提供服务调用的例子，我明天看下这里的代码提交哈～
> 
> ok，辛苦

@shouyuwang 这里可以加上服务注册与发现模块的依赖，麻烦您看下单测问题呢

**Comment by SkyeBeFreeman** [comment]
Please add information of this PR to CHANGELOG.md in root. Will you cherry-pick this commit to branch of 2020.0 and 2021.0?

**Comment by shouyuwang** [comment]
> Please add information of this PR to CHANGELOG.md in root. Will you cherry-pick this commit to branch of 2020.0 and 2021.0?

ok

**Pull request merged**
